# Generated by Django 4.0 on 2022-06-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
